### ISSUE TITLE
Incorrect visualization

### ISSUE THREAD

**Issue by bpfliegel** [cezannec/P1_Facial_Keypoints#1]
In def visualize_output(test_images, test_outputs, gt_pts=None, batch_size=10):

        # un-transform the key_pts data
        key_pts = test_outputs.data

should be correctly:

        # un-transform the key_pts data
        key_pts = test_outputs[i].data

**Comment by cezannec** [comment]
Thank you so much for identifying this issue! I've updated the visualize_output function so that it should work properly now.
