### ISSUE TITLE
Flattening of key points

### ISSUE THREAD

**Issue by bpfliegel** [cezannec/P1_Facial_Keypoints#2]
In train_net, flattening of key points are done like this:
key_pts = key_pts.view(1, -1)

I think it would be more correct to do it like that:
key_pts = key_pts.view(key_pts.size(0), -1)

**Comment by letyrodridc** [comment]
I agree, it's flattening the batch_size

Before:
torch.Size([10, 68, 2])
After:
torch.Size([1, 1360])

I also agree with the fix, good call Balint!

**Comment by bpfliegel** [comment]
No, it's flattening just the keypoint dims, not the minibatch size - so vice-versa:

Assume you have a minibatch size of 10, you will get:
images: torch.Size([10, 1, 224, 224])
key_pts: torch.Size([10, 68, 2])

So what you want is to have the keypoints dimension flattened:
key_pts: torch.Size([10, 136])

So you have to do: key_pts = key_pts.view(key_pts.size(0), -1)
and not: key_pts = key_pts.view(1, -1) - which makes no sense for me.

**Comment by letyrodridc** [comment]
Yes, I wasn't clear. I wrote how it's working the current notebook.
It's changing the dimension to torch.Size([1, 1360]) instead of torch.Size([10, 136]) as you proposed that it correct.

**Comment by bpfliegel** [comment]
:)
