### ISSUE TITLE
README.md "Windows" need to be included in instructions

### ISSUE THREAD

**Issue by letyrodridc** [cezannec/P1_Facial_Keypoints#4]
It says:
```
Install PyTorch and torchvision.

Linux or Mac:
conda install pytorch torchvision -c pytorch 
```

But Windows is missing.

**Comment by bpfliegel** [comment]
For windows (CPU) it should be - (untested, likely correct I can test, if needed):
conda install -c peterjc123 pytorch-cpu
pip install torchvision

For GPU, it's a little more complicated to describe, but I can if needed.

**Comment by bpfliegel** [comment]
For Windows, a hack is needed for rebuild_tensor_v2, and num_workers must be set to 0.
