### ISSUE TITLE
Minor issues: list of typos

### ISSUE THREAD

**Issue by hhprogram** [cezannec/P1_Facial_Keypoints#5]
(1) Section: "Load and Visualize Data" notebook 1. last sentence says "fraes", should be "frames"
(2) Section: "Dataset class" section notebook 1. "mormalizing images...", should be "normalizing"..
(3) Section: first paragraph of notebook 2. "..data your working with...", should be "you're"
(4) Section: Apply the model on a test sample notebook 2, "1. Extract the image and groud truth keypoints from a sample", should be 'ground'
(5) Section: Training and Initial Observation notebook 2, "..you're encouraged to start of with", should be "start off"
(6) Section: Feature maps notebook 2 "...each of these ernesl detects...", should be "kernels"
(7) Section: Face and Facial Keypoint detection notebook 3 "The neural network expectes a Tensor ", should be "expects"

These issues are obviously minor, but I think they are easy to fix and make the project look more professional and gives the student a sense that the Udacity team really went through this project thoroughly before giving it to them.

**Comment by hhprogram** [comment]
(9) In "Feature maps" section of notebook 2:
"Each CNN has at least one convolutional layer that is comprosed of stacked filters ", should be 'composed'

**Comment by hhprogram** [comment]
(10) Notebook 3 The title "The complete the pipeline" near the top, should be "The complete pipeline" or "To complete the pipeline" not sure

**Comment by cezannec** [comment]
Hello, and thank you for taking careful note of these errors! I agree that these small details can make a difference and I've updated these project files :)
