### ISSUE TITLE
In train net, use the batch_size in the print

### ISSUE THREAD

**Issue by letyrodridc** [cezannec/P1_Facial_Keypoints#9]
It says
```
batch_i % 10 == 9
```

Instead of 
```
batch_i % batch_size == batch_size - 1 
```

**Comment by cezannec** [comment]
batch_i % 10 == 9 means that the loss will print every 10 batches. You should be able to change this depending on how often you want it to print, ex. you could write batch_i % 100 == 99 if you wanted the loss to print out every 100 batches, so it should be a free parameter :)
